### PR TITLE
fix(Pulscen): change the link cursor

### PR DESCRIPTION
**Pull request by DanteDeGrave**
[PATCH]: change the link cursor
https://jira.railsc.ru/browse/PC4-28295

### CODE REVIEW

**Comment by DanteDeGrave** [comment]
@Saymell => @ Comediant24

**Review by Saymell — APPROVED** [review]

**Comment by Saymell** [comment]
@Comediant24

**Review by Comediant24 — APPROVED** [review]
:see_no_evil:

**Comment by Comediant24** [comment]
14.44.2

**Pull request merged**
