### PR TITLE
feature(BLIZKO): add new styles to the slider [skip ci]

### PR DESCRIPTION
**Pull request by Sportgirl55**
[PATCH]: исправит размеры блока карусели

 https://jira.railsc.ru/browse/BPC-23175

### CODE REVIEW

**Comment by Sportgirl55** [comment]
@Comediant24 => @ woklisgm

**Review by Comediant24 — APPROVED** [review]

**Comment by Comediant24** [comment]
@woklisgm

**Review by woklisgm — APPROVED** [review]

**Comment by Sportgirl55** [comment]
@Comediant24

**Comment by Sportgirl55** [comment]
@Comediant24

**Comment by Comediant24** [comment]
[14.100.0](https://github.com/abak-press/apress-ui/pull/642)

**Pull request merged**
