### PR TITLE
fix(lookmart): fix social-networks block alignment

### PR DESCRIPTION
**Pull request by VeraVLVlas**
[MINOR] исправит выравнивание блоков соц.сетей
https://jira.railsc.ru/browse/SG-7582

### CODE REVIEW

**Comment by VeraVLVlas** [comment]
@Saymell => @ idbolshakov

**Review by Saymell — APPROVED** [review]
@idbolshakov

**Review by idbolshakov — APPROVED** [review]

**Comment by VeraVLVlas** [comment]
@Comediant24

**Comment by Comediant24** [comment]
14.31.0

**Pull request merged**
